In [2]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.decomposition import PCA
import jieba
import numpy as np
from sklearn.impute import SimpleImputer

特征预处理PCA

In [3]:
# 降维
def pca():
    '''
    目的：数据维数压缩，降低原数据维数(复杂度)

    :return:
    '''
    # n_components=:1.整数：如果有4个特征，只保留3个特征；2.小数:90~95%保留的成分有90%~95%的代表性
    pca = PCA(n_components=3)
    data = pca.fit_transform([[2, 8, 4, 5], [6, 3, 0, 8],
                              [5, 4, 9, 1],[6, 7, 9, 2]])
    print(data)
    return None
pca()



[[ 1.42614233  3.84729403 -0.47638925]
 [ 7.09016001 -1.93393691  0.22807681]
 [-4.30119225 -1.86011188 -1.26579187]
 [-4.21511009 -0.05324524  1.51410431]]
