In [1]:
from sklearn.datasets import load_iris, fetch_20newsgroups, load_boston
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score

In [10]:
# 数据集加载
# 鸢尾花数据集，查看特征，目标样本量
li = load_iris()
print('获取特征值:')
print(type(li.data))
print(li.data.shape)
print('查看目标值:')
print(li.target)
# 查看数据描述
print(li.DESCR)
# 查看特征名,新闻数据，手写数字、回归数据集没有
print(li.feature_names)
# 标签名，回归数据集没有
print(li.target_names)
print('*'*50)

获取特征值:
<class 'numpy.ndarray'>
(150, 4)
查看目标值:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correla

In [11]:
# 数据集分割
# 注意返回值, 训练集 train  x_train, y_train测试集  test   x_test, y_test，顺序千万别搞错了
# x-数据集的特征值，y-数据集的标签值
# 默认是乱序的,random_state为了确保两次的随机策略一致，就会得到相同的随机数据，往往会带上
# train_test_split(
x_train, x_test, y_train, y_test = train_test_split(li.data, li.target, test_size=0.2, random_state=1)
print('训练集的特征值和目标值:', x_train, y_train)
print('训练集特征值shape:', x_train.shape)
print('-'*50)
print('测试机的特征值和目标值:', x_test, y_train)
print('测试集特征值shape:', x_test.shape)

训练集的特征值和目标值: [[6.1 3.  4.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.6 2.5 3.9 1.1]
 [6.4 2.8 5.6 2.1]
 [5.8 2.8 5.1 2.4]
 [5.3 3.7 1.5 0.2]
 [5.5 2.3 4.  1.3]
 [5.2 3.4 1.4 0.2]
 [6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]

In [2]:
news = fetch_20newsgroups(subset='all', data_home='data')
# 默认只下载训练集.subset='all'：训练集和测试集都要;data_home='data'指定下载路径
print(news.DESCR)
print('-'*50)
print(news.data[0])
print('-'*50)

print(news.target[0])  # 目标值第一个的类别值
print(len(news.data)) # 多少篇文章
print('-'*50)
print(news.target) # 有二十个类别值
print('-'*50)
print(max(news.target), min(news.target))

.. _20newsgroups_dataset:

The 20 newsgroups text dataset
------------------------------

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`~sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

**Data Set Characteristics:**

    =================   ==========
    Classes                     20
    Samples total            18846
    Dimensionality

In [16]:
# 波士顿房价
lb = load_boston()
print('获取第一个特征值:')
print(lb.data[0])
print(lb.data.shape)
print('获取第一个目标值:')
# 输出的是房价
print(lb.target[0])
print('-'*50)
print('描述:')
print(lb.DESCR)
print('-'*50)
print(lb.feature_names)
# 目标值是回归值无目标值标签名
# print(lb.target_names)

获取第一个特征值:
[6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
 4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]
(506, 13)
获取第一个目标值:
24.0
--------------------------------------------------
描述:
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior

C:\Users\life\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the C

# 分类估计器(算法) estimator

In [19]:
# K近邻算法 KNN
# n_neighbors=n,n就是选择的邻居数,int,默认为5；
# k_neighbors 查找默认使用的邻居量
# 处理Facebook数据
data = pd.read_csv('../python_ml/data/FBlocation/train.csv')
print(data.head(0))
print(data.shape)
# 处理数据
# 1.缩小数据，查找数据，减少计算时间
data = data.query("x > 1.0 & x <1.25 & y > 2.5 & y < 2.75")
# 处理时间的数据
time_values = pd.to_datetime(data['time'],unit = 's')
print(time_values)

Empty DataFrame
Columns: [row_id, x, y, accuracy, time, place_id]
Index: []
(29118021, 6)
600        1970-01-01 18:09:40
957        1970-01-10 02:11:10
4345       1970-01-05 15:08:02
4735       1970-01-06 23:03:03
5580       1970-01-09 11:26:50
                   ...        
29100203   1970-01-01 10:33:56
29108443   1970-01-07 23:22:04
29109993   1970-01-08 15:03:14
29111539   1970-01-04 00:53:41
29112154   1970-01-08 23:01:07
Name: time, Length: 17710, dtype: datetime64[ns]


In [20]:
time_values = pd.DatetimeIndex(time_values)
print(time_values)

DatetimeIndex(['1970-01-01 18:09:40', '1970-01-10 02:11:10',
               '1970-01-05 15:08:02', '1970-01-06 23:03:03',
               '1970-01-09 11:26:50', '1970-01-02 16:25:07',
               '1970-01-04 15:52:57', '1970-01-01 10:13:36',
               '1970-01-09 15:26:06', '1970-01-08 23:52:02',
               ...
               '1970-01-07 10:03:36', '1970-01-09 11:44:34',
               '1970-01-04 08:07:44', '1970-01-04 15:47:47',
               '1970-01-08 01:24:11', '1970-01-01 10:33:56',
               '1970-01-07 23:22:04', '1970-01-08 15:03:14',
               '1970-01-04 00:53:41', '1970-01-08 23:01:07'],
              dtype='datetime64[ns]', name='time', length=17710, freq=None)


In [21]:
print(type(data))
data.insert(data.shape[1], 'day', time_values.day)
# data.shape[1]:插入到最后
data.insert(data.shape[1], 'hour', time_values.hour)
data.insert(data.shape[1], 'weekday', time_values.weekday)
# 删除时间戳
data = data.drop(['time'], axis=1)
print('-'*50)
print(data)

<class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
            row_id       x       y  accuracy    place_id  day  hour  weekday
600            600  1.2214  2.7023        17  6683426742    1    18        3
957            957  1.1832  2.6891        58  6683426742   10     2        5
4345          4345  1.1935  2.6550        11  6889790653    5    15        0
4735          4735  1.1452  2.6074        49  6822359752    6    23        1
5580          5580  1.0089  2.7287        19  1527921905    9    11        4
...            ...     ...     ...       ...         ...  ...   ...      ...
29100203  29100203  1.0129  2.6775        12  3312463746    1    10        3
29108443  29108443  1.1474  2.6840        36  3533177779    7    23        2
29109993  29109993  1.0240  2.7238        62  6424972551    8    15        3
29111539  29111539  1.2032  2.6796        87  3533177779    4     0        6
29112154  29112154  1.1070  2.5419       178  4932578245    8   

In [22]:
# 删除签到数量少于n个目标位置
place_count = data.groupby('place_id').count()
place_count

row_id     x     y  accuracy   day  hour  weekday
place_id                                                     
1012023972       1     1     1         1     1     1        1
1057182134       1     1     1         1     1     1        1
1059958036       3     3     3         3     3     3        3
1085266789       1     1     1         1     1     1        1
1097200869    1044  1044  1044      1044  1044  1044     1044
...            ...   ...   ...       ...   ...   ...      ...
9904182060       1     1     1         1     1     1        1
9915093501       1     1     1         1     1     1        1
9946198589       1     1     1         1     1     1        1
9950190890       1     1     1         1     1     1        1
9980711012       5     5     5         5     5     5        5

[805 rows x 7 columns]

In [23]:
#
tf = place_count[place_count.row_id>3].reset_index()  # reset_index删除索引后重制连续
# 根据设定目标值开始过滤
data = data[data['place_id'].isin(tf.place_id)]
data

row_id       x       y  accuracy    place_id  day  hour  weekday
600            600  1.2214  2.7023        17  6683426742    1    18        3
957            957  1.1832  2.6891        58  6683426742   10     2        5
4345          4345  1.1935  2.6550        11  6889790653    5    15        0
4735          4735  1.1452  2.6074        49  6822359752    6    23        1
5580          5580  1.0089  2.7287        19  1527921905    9    11        4
...            ...     ...     ...       ...         ...  ...   ...      ...
29100203  29100203  1.0129  2.6775        12  3312463746    1    10        3
29108443  29108443  1.1474  2.6840        36  3533177779    7    23        2
29109993  29109993  1.0240  2.7238        62  6424972551    8    15        3
29111539  29111539  1.2032  2.6796        87  3533177779    4     0        6
29112154  29112154  1.1070  2.5419       178  4932578245    8    23        3

[16918 rows x 8 columns]

In [24]:
# 取特征值、目标值
y = data['place_id']  # 目标值
# 删除目标值，保留特征值
x = data.drop(['place_id'], axis=1)
# 删除无用特征值
x = x.drop(['row_id'], axis=1)
print('进行数据分割：')
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=1)
print('开始特征工程标准化:')
std = StandardScaler()
x_train = std.fit_transform(x_train)
print(std.mean_)
print(std.var_)
print('测试集：')
x_test = std.transform(x_test)
print(std.mean_)
# KNN算法流程# # 超参数，可以通过设置n_neighbors=5，来调整结果好坏
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train, y_train)# fit训练
# 预测结果
y_predict = knn.predict(x_test)
print('预测的目标值位置:', y_predict)
print('预测的准确率:', knn.score(x_test, y_test))

进行数据分割：
开始特征工程标准化:
[ 1.12294552  2.63278329 81.87142857  5.1044335  11.44985222  3.10305419]
[5.98796912e-03 4.87604476e-03 1.23873587e+04 7.31067000e+00
 4.83485689e+01 2.82780348e+00]
测试集：
[ 1.12294552  2.63278329 81.87142857  5.1044335  11.44985222  3.10305419]
预测的目标值位置: [1913341282 1097200869 6097504486 ... 1812226671 8258328058 3992589015]
预测的准确率: 0.46897163120567376


朴素贝叶斯

In [15]:
# 朴素贝叶斯进行文本分类
# news = fetch_20newsgroups(subset='all', data_home='data')  上面有
print(len(news.data))
print(news.target) # 特征值
print('标签名:', news.target_names)
print('*'*80)
print('数据分割:')
x_train,x_test,y_train,y_test = train_test_split(news.data, news.target, test_size=0.25,random_state=1)
print('特征抽取:')
tf = TfidfVectorizer() # 如果是中文，先分词，在空格拼
# 训练集重要性词条统计
x_train = tf.fit_transform(x_train)
tf.get_feature_names()[70000] # 获取第70000个特征值
# 测试集重要词统计
x_test = tf.transform(x_test)
# 朴素贝叶斯算法预测
mlt = MultinomialNB()
# 朴素贝叶斯不支持稀疏矩阵，得自己转
print(x_train.toarray())
print('-'*80)
# 训练
mlt.fit(x_train, y_train)
# 预测
y_predict = mlt.predict(x_test)
print('预测的文章类别:', y_predict)
# 评估
print('评估准确率:', mlt.score(x_test,y_test))

18846
[10  3 17 ...  3  1  7]
标签名: ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
********************************************************************************
数据分割:
特征抽取:


C:\Users\life\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
--------------------------------------------------------------------------------
预测的文章类别: [16 19 18 ... 13  7 14]
评估准确率: 0.8518675721561969


In [16]:
# support是真实的为那个类别的有多少个样本
print("每个类别的精确率和召回率：", classification_report(y_test, y_predict, target_names=news.target_names))


每个类别的精确率和召回率：                           precision    recall  f1-score   support

             alt.atheism       0.91      0.77      0.83       199
           comp.graphics       0.83      0.79      0.81       242
 comp.os.ms-windows.misc       0.89      0.83      0.86       263
comp.sys.ibm.pc.hardware       0.80      0.83      0.81       262
   comp.sys.mac.hardware       0.90      0.88      0.89       234
          comp.windows.x       0.92      0.85      0.88       230
            misc.forsale       0.96      0.67      0.79       257
               rec.autos       0.90      0.87      0.88       265
         rec.motorcycles       0.90      0.95      0.92       251
      rec.sport.baseball       0.89      0.96      0.93       226
        rec.sport.hockey       0.95      0.98      0.96       262
               sci.crypt       0.76      0.97      0.85       257
         sci.electronics       0.84      0.80      0.82       229
                 sci.med       0.97      0.86      0.91      

In [17]:
# 把0-19总计20个分类，变为0和1,多分类变二分类
y_test1 = np.where(y_test == 5, 1, 0) # 如果测试集的类别等于5的，就设置为1，不等于5的设置为0
print(y_test1.sum())
y_predict1 = np.where(y_predict == 5, 1, 0)  # 如果预测的类别等于5的，就设置为1，不等于5的设置为0
print(y_predict1.sum())
# roc_auc_score的y_test只能是二分类,针对多分类如何计算AUC
print("AUC指标：", roc_auc_score(y_test1, y_predict1))

230
214
AUC指标： 0.924078924393225


# 网格搜索

In [25]:
param = {"n_neighbors": [3, 5, 10, 12, 15]}
#
# 进行网格搜索，cv=3是3折交叉验证，用其中2折训练，1折验证
gc = GridSearchCV(knn, param_grid=param, cv=3)

gc.fit(x_train, y_train)  #特征分为训练集和验证集

# 预测准确率
print("在测试集上准确率：", gc.score(x_test, y_test))
print("在交叉验证当中最好的结果：", gc.best_score_)
print("选择最好的模型是：", gc.best_estimator_)
print("每个超参数每次交叉验证的结果：", gc.cv_results_)

C:\Users\life\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


在测试集上准确率： 0.46971040189125296
在交叉验证当中最好的结果： 0.4504438826031143
选择最好的模型是： KNeighborsClassifier(n_neighbors=10)
每个超参数每次交叉验证的结果： {'mean_fit_time': array([0.00434756, 0.00433056, 0.00466681, 0.00466649, 0.00442743]), 'std_fit_time': array([0.0004616 , 0.0004684 , 0.00047243, 0.00047165, 0.00042089]), 'mean_score_time': array([0.04443391, 0.04917296, 0.05657196, 0.07620994, 0.06474352]), 'std_score_time': array([0.00124683, 0.00054165, 0.00114924, 0.01247107, 0.00106556]), 'param_n_neighbors': masked_array(data=[3, 5, 10, 12, 15],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_neighbors': 3}, {'n_neighbors': 5}, {'n_neighbors': 10}, {'n_neighbors': 12}, {'n_neighbors': 15}], 'split0_test_score': array([0.42523641, 0.44503546, 0.44503546, 0.44621749, 0.44237589]), 'split1_test_score': array([0.41945019, 0.44516701, 0.44841856, 0.44546261, 0.4392551 ]), 'split2_test_score': array([0.43393438, 0.45167012, 0.45787762, 0.45