In [1]:
import numpy as np
import time
import random


In [8]:
# 根据数组运算计算效率
# 1.python代码实现sum时间
lst = []
for i in range(100000000):
    lst.append(random.random())
t1 = time.time()
sum1 = sum(lst)
t2 = time.time()

lst1 = np.array(lst)
t3 = time.time()
sum2 = np.sum(lst1)
t4= time.time()
print(t2-t1,t4-t3)


0.45282554626464844 0.05332493782043457


In [10]:
# np 创建一维数组
t1 = np.array([1, 2, 3]) # 直接传入数组
print(type(t1))
print(t1)

t2 = np.array(range(10)) # 随机生成数组
print(type(t2))
print(t2)

t3 = np.arange(0,20,4)  # 使用np自带的arrange生成数组
print(type(t3))
print(t3)


<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[ 0  4  8 12 16]


In [16]:
# 二维数组
list1=[[1,3],[5,7],[9,11]]
twoArray = np.array(list1) # 创建二维数据
print(type(twoArray))
# 获取数组维度
print(twoArray.ndim)
# 获取数组形状；shape(行，列）
print(twoArray.shape)
# 获取元素个数
print(twoArray.size)




<class 'numpy.ndarray'>
2
(3, 2)
6


In [33]:
# 数组的形状调整
s1 = np.array([[1,3,5],[7,9,11]])
s1 = s1.reshape(3,2)
print(s1)
# 变为一维数组
s2 = s1.reshape((6,), order = 'F') # 以列展开成一维数组
s3 = s1.reshape((6,), order = 'C') # C以行展开数组
s4 = s1.flatten(order='F')  # flatten返回一维数组
print(s2)
print(s3)
print(s4)
# 数组的形状
t = np.arange(6)
print(t)  # [0 1 2 3 4]
print(t.shape)  # (5,)
# 变成二维数组
t1 = t.reshape(3,2)
print(t1)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[ 1  5  9  3  7 11]
[ 1  3  5  7  9 11]
[ 1  5  9  3  7 11]
[0 1 2 3 4 5]
(6,)
[[0 1]
 [2 3]
 [4 5]]


In [34]:
# np.array 与python list的互相转换
t = np.arange(10)
lst = t.tolist()
print(type(lst))
print(lst)


<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
